alias code='codium'
alias df='df -h'
alias l='ls -lh --color=auto'
alias ll='ls -lah --color=auto'
alias open='xdg-open'
alias vi='vim'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ..='cd ..'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias dnf='sudo dnf'
alias pacman='sudo pacman'
